import re
import Strings


def warn(line, warning):
	print(f"Warning (line {line}): {warning}")


def error(line, error):
	print(f"Error (line {line}): {error}")


class Checker:
	def __init__(self, code=None, debug=None):
		self.DEBUG = debug
		self.code = code

	def check(self):
		w = Strings.StyleWarning
		e = Strings.StyleError
		code = self.code
		for i, line in enumerate(code):
			n = i - 2  # Ignore first 3 lines generated by DrRacket
			if n == 3 and not checkStudentNum(line):
				error(n, e.STUDENTNUM)
			if n == 5 and not checkFileLabel(line):
				error(n, e.FILELABEL)


# Helper functions
def isComment(line):
	return line.startswith(';;')


# Check functions
# Check for 8-digit UWaterloo student number
def checkStudentNum(line):
	res = re.search(r"\(\d{8}\)", line)
	return res and isComment(line)


# Check for Assignment/Problem number
def checkFileLabel(line):
	res = re.search(r"Assignment \d+, Problem \d+", line)
	return res and isComment(line)
